// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BetterSalesman.iOS
{
	public partial class UIButtonRounded : UIButton
	{
		public UIButtonRounded (IntPtr handle) : base (handle)
		{
            Layer.MasksToBounds = true;
            Layer.CornerRadius = 5;
		}
	}
}
