// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using BetterSalesman.Core.BusinessLayer;
using BetterSalesman.Core.ServiceAccessLayer;
using BetterSalesman.Core.BusinessLayer.Managers;

namespace BetterSalesman.iOS
{
    public partial class ArgumentsDetail : BaseUIViewController
	{
        public Argument Argument;
        
		public ArgumentsDetail (IntPtr handle) : base (handle)
		{
		}
        
        #region Lifecycle
        
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            
            labelFeature.Text = Argument.Feature;
            labelBenefit.Text = Argument.Benefit;
            
            if ( Argument.MyRating > 0 && Argument.UserId == UserManager.LoggedInUser().Id )
            {
                chooseRating.Enabled = false;
            } 
            else
            {
                chooseRating.ValueChanged += (sender, e) =>
                {
                    ShowHud(I18n.Sending);
                
                    ServiceProviderArgument.Instance.Rate(
                        Argument,
                        chooseRating.SelectedSegment + 1,
                        success =>
                        {
                    
                            HideHud();
                            chooseRating.Enabled = false;
                        },
                        error =>
                        {
                            HideHud();
                            ShowAlert(I18n.ErrorConnectionTimeout);
                        }
                    );
                
                    Debug.WriteLine("Changed value of rating picker " + chooseRating.SelectedSegment);
                };
            }
        }
        
        #endregion
	}
}
