// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using BetterSalesman.Core.BusinessLayer;
using BetterSalesman.Core.ServiceAccessLayer;
using BetterSalesman.Core.BusinessLayer.Managers;

namespace BetterSalesman.iOS
{
    public partial class ArgumentsDetail : BaseUIViewController
	{
        public Argument Argument;
        
		public ArgumentsDetail (IntPtr handle) : base (handle)
		{
		}
        
        #region Lifecycle
        
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            
            updateView();
            
            if ( Argument.MyRating > 0 && Argument.UserId == UserManager.LoggedInUser().Id )
            {
                chooseRating.Enabled = false;
            } 
            else
            {
                chooseRating.ValueChanged += (sender, e) =>
                {
                    if (!IsNetworkAvailable())
                    {
                        ShowAlert(ServiceAccessError.ErrorHostUnreachable.LocalizedMessage);
                        return;
                    }
                        
                    ShowHud(I18n.Sending);
                
                    ServiceProviderArgument.Instance.Rate(
                        Argument,
                        chooseRating.SelectedSegment + 1,
                        updatedArgument =>
                        {
                            Argument = updatedArgument;
                            updateView();
                            HideHud();
                        },
                        errorMessage =>
                        {
                            chooseRating.SelectedSegment = -1;
                            HideHud();
                            ShowAlert(errorMessage);
                        }
                    );
                };
            }
        }
        
        void updateView()
        {
            labelFeature.Text = Argument.Feature;
            labelBenefit.Text = Argument.Benefit;
            
            if (Argument.Rated || Argument.UserId == UserManager.LoggedInUser().Id)
            {
                if (Argument.UserId != UserManager.LoggedInUser().Id)
                {
                    chooseRating.SelectedSegment = Argument.MyRating - 1;
                } 
                
                chooseRating.Enabled = false;
            }
        }
        
        #endregion
	}
}
