// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using BetterSalesman.Core.BusinessLayer;

namespace BetterSalesman.iOS
{
	public partial class ArgumentsForm : UIViewController
	{
        public Argument Argument;
        
		public ArgumentsForm (IntPtr handle) : base (handle)
		{
		}
	}
}
