// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.UIKit;

namespace BetterSalesman.iOS
{
	public sealed partial class UISliderActivity : UISlider
	{
        const string imageEmpty = "progress_bg";
        const string imageFull = "progress_full";
        
		public UISliderActivity (IntPtr handle) : base (handle)
		{
            var minImage = UIImage.FromBundle(imageEmpty).CreateResizableImage(new UIEdgeInsets(3,3,3,3));
            var maxImage = UIImage.FromBundle(imageFull).CreateResizableImage(new UIEdgeInsets(3,3,3,3));
            var thumbImage = UIImage.FromBundle("");
            
            SetThumbImage(thumbImage, UIControlState.Normal);
            SetMinTrackImage(minImage, UIControlState.Normal);
            SetMaxTrackImage(maxImage, UIControlState.Normal);
		}
        
        public override System.Drawing.RectangleF TrackRectForBounds(System.Drawing.RectangleF forBounds)
        {
            var bounds = base.TrackRectForBounds(forBounds);
            
            bounds.Height = 14;
            
            return bounds;
        }
	}
}
