// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BetterSalesman.iOS
{
	public partial class ArgumentFormViewController : UIViewController
	{
		public ArgumentFormViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
